import time
import json
import asyncio
import logging
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from api.models.request import QueryRequest
from api.models.response import QueryResponse
import api.main as app_state

logger = logging.getLogger(__name__)
router = APIRouter()


@router.post("/query", response_model=QueryResponse)
async def query(request: QueryRequest):
    """
    Full RAG query: retrieve + generate, return complete response.
    Use this endpoint for programmatic API access.
    """
    pipeline = app_state.retrieval_pipeline
    gen = app_state.generator
    cache_client = app_state.cache
    bench = app_state.benchmarker

    if pipeline is None:
        raise HTTPException(status_code=503, detail="Service not initialized")

    t_start = time.time()

    # Cache lookup
    if request.use_cache:
        cached = cache_client.get(request.query, top_k=request.top_k, mode=request.retrieval_mode)
        if cached:
            bench.record_e2e((time.time() - t_start) * 1000, cache_hit=True)
            cached["cached"] = True
            return QueryResponse(**cached)

    try:
        # Retrieval
        t_ret = time.time()
        docs = pipeline.retrieve(
            query=request.query,
            top_k_retrieval=request.top_k * 4,
            top_k_final=request.top_k,
            filter=request.filter
        )
        retrieval_ms = (time.time() - t_ret) * 1000
        bench.record_retrieval(retrieval_ms)

        if not docs:
            raise HTTPException(status_code=404, detail="No relevant documents found")

        # Generation
        t_gen = time.time()
        result = gen.generate(query=request.query, retrieved_docs=docs)
        generation_ms = (time.time() - t_gen) * 1000
        e2e_ms = (time.time() - t_start) * 1000

        bench.record_generation(generation_ms, len(result["answer"].split()))
        bench.record_e2e(e2e_ms, cache_hit=False)

        response_data = {
            **result,
            "cached": False,
            "retrieval_latency_ms": round(retrieval_ms, 2),
            "generation_latency_ms": round(generation_ms, 2),
            "e2e_latency_ms": round(e2e_ms, 2)
        }

        if request.use_cache:
            cache_client.set(request.query, response_data, top_k=request.top_k, mode=request.retrieval_mode)

        return QueryResponse(**response_data)

    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Query error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"Internal error: {str(e)}")


@router.post("/query/stream")
async def stream_query(request: QueryRequest):
    """
    Streaming RAG query using Server-Sent Events (SSE).
    
    Client receives tokens as they are generated by GPT-4o.
    Each event: data: {"token": "<token_string>"}
    Final event before [DONE]: data: {"citations": [...], "metadata": {...}}
    Terminal event: data: [DONE]
    
    Use this endpoint for the Streamlit frontend and browser clients.
    """
    pipeline = app_state.retrieval_pipeline
    gen = app_state.generator

    if pipeline is None:
        raise HTTPException(status_code=503, detail="Service not initialized")

    try:
        docs = pipeline.retrieve(
            query=request.query,
            top_k_retrieval=request.top_k * 4,
            top_k_final=request.top_k,
            filter=request.filter
        )

        if not docs:
            async def empty_stream():
                yield f"data: {json.dumps({'token': 'No relevant documents found for this query.'})}\n\n"
                yield "data: [DONE]\n\n"
            return StreamingResponse(empty_stream(), media_type="text/event-stream")

        async def sse_stream():
            full_response = ""
            async for token in gen.astream_generate(
                query=request.query,
                retrieved_docs=docs
            ):
                if token.startswith("\n\n[CITATIONS]"):
                    citations_json = token.replace("\n\n[CITATIONS]", "").replace("[/CITATIONS]", "")
                    yield f"data: {json.dumps({'citations': json.loads(citations_json)})}\n\n"
                else:
                    full_response += token
                    yield f"data: {json.dumps({'token': token})}\n\n"
                    await asyncio.sleep(0)
            yield "data: [DONE]\n\n"

        return StreamingResponse(
            sse_stream(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "X-Accel-Buffering": "no",
                "Connection": "keep-alive"
            }
        )

    except Exception as e:
        logger.error(f"Stream error: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=str(e))